#cloud-config
autoinstall:
  version: 1
  # System user configuration
  identity:
    hostname: ubuntu-server
    username: myuser
    password: "$6$rounds=4096$eJycWICZPfnZgr2Q$9hHjL1mpMoPtb/av.eYMaMZg8FZ7qFFsnfrlyFP.b6QelMiybl4QmddLDInffnE7kxAvu8a11h23rc9UM3Sp7/"
  ssh:
    install-server: yes
    allow-pw: no
  # Disk layout configuration
  storage:
    layout:
      name: lvm
      match:
        size: largest
    config:
      - type: disk
        id: disk0
        match:
          size: largest
        ptable: gpt
        preserve: false
        wipe: superblock
        name: ''
        grub_device: true
        partitions:
          - type: partition
            id: boot-partition
            size: 512M
            flag: boot
          - type: partition
            id: lvm-partition
            size: -1
      - type: lvm_volgroup
        id: vg0
        name: vg0
        devices:
          - lvm-partition
      - type: lvm_lv
        id: lv-root
        name: root
        volgroup: vg0
        size: 20G
        filesystem: ext4
        mountpoint: /
      - type: lvm_lv
        id: lv-swap
        name: swap
        volgroup: vg0
        size: 2G
        mountpoint: none
        filesystem: swap
      - type: lvm_lv
        id: lv-home
        name: home
        volgroup: vg0
        size: -1
        filesystem: ext4
        mountpoint: /home
  # Network configuration
  network:
    network:
      version: 2
      ethernets:
        ens3:
          dhcp4: true
  # Packages to install and remove
  packages:
    - vim
    - htop
    - git
    - curl
  package_update: true
  package_upgrade: true
  late-commands:
    - curtin in-target --target=/ apt-get remove --purge -y snapd
    - curtin in-target --target=/ apt-get autoremove --purge -y
  # System configuration after installation
  user-data:
    timezone: America/New_York
    disable_root: true
  kernel:
    package: linux-generic
  locale: en_US.UTF-8
